sudo: false
cache: bundler
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - 2.5.0
  - ruby-head
  - jruby-9.1.14.0
gemfile:
  - gemfiles/Gemfile.rails-5-0-stable
  - gemfiles/Gemfile.rails-5-1-stable
  - gemfiles/Gemfile.rails-5-2-stable
  - Gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.10
      gemfile: Gemfile
    - rvm: jruby-9.1.14.0
      gemfile: Gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: jruby-9.1.14.0
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: jruby-9.1.14.0
      gemfile: gemfiles/Gemfile.rails-5-1-stable
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-5-1-stable
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5-1-stable
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-1-stable
    - rvm: jruby-9.1.14.0
      gemfile: gemfiles/Gemfile.rails-5-2-stable
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-5-2-stable
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5-2-stable
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-2-stable

before_install:
  - gem update --system

notifications:
  email: false
